### ISSUE TITLE
Linuxのサポートはされてますか？

### ISSUE THREAD

**Issue by HidemaruOwO** [k896951/voxsay#2]
このプロジェクトをLinuxで使おうと考えているのですが。
そもそも大前提としてLinuxはサポートされているのでしょうか？

**Comment by k896951** [comment]
明示的にLinuxをサポートしていません。
取得した音声を再生するためにNAudioを利用していますが、この部分のLinux向け実装を私は知りません。そのため案を出す事もできません。すみません。
